### ISSUE TITLE
help - "testless build" if test fails

### ISSUE THREAD

**Issue by andreabisello** [hendrikdp/bamboo-jest-reporter#1]
if test fails, atlassian bamboo thinks there is no test in the run.

if all the test pass, 

![image](https://user-images.githubusercontent.com/2149815/67076580-b45a2480-f18d-11e9-96d8-9e5eb1e986a2.png)

bamboo gives me test results

![image](https://user-images.githubusercontent.com/2149815/67076615-c6d45e00-f18d-11e9-8669-825351f842f2.png)

if one test fails,

atlassian think there is no test

![image](https://user-images.githubusercontent.com/2149815/67076644-da7fc480-f18d-11e9-8848-51f412008993.png)

i think the solution is there https://github.com/hendrikdp/bamboo-jest-reporter#usage but i'm not able to understand.

can you explain me better?

thanks

**Comment by hendrikdp** [comment]
This is because the 'npm test' task in your job failed... If one task in your job fails, it won't execute the next one (meaning that the 'mocha parser' task will be skipped). To prevent your job from failing on 'npm test', you should send exit code 0 ('exit 0') in your bamboo task...

In your job:
- add task
- select script
- interpreter: bin/sh (bash)
In the script test if 'npm test' fails, if it does exit your job with 'exit 0'
if ! npm test
then
    echo "The automated jest tests did not pass. Please check the tests-tab"
    **exit 0**
fi

Hope this helps!

Kind rgds,

Hendrik

**Comment by andreabisello** [comment]
@hendrikdp  thanks for your help.

i already read https://github.com/hendrikdp/bamboo-jest-reporter#usage ,

but i'm on a windows environment.

i tried

![image](https://user-images.githubusercontent.com/2149815/67759597-062d6500-fa40-11e9-914e-2067e69e8236.png)

exit 0 was not considered ( bamboo report No failed test found. A possible compilation error occurred. )

so i edited package.json adding the script test

![image](https://user-images.githubusercontent.com/2149815/67759627-16454480-fa40-11e9-9c85-4a5999b34f47.png)

but

if ! npm test
then
echo "The automated jest tests did not pass. Please check the tests-tab"
exit 0

in windows environment will not work,

so i tried to edit the test script adding the *testFailureExitCode* flag

![image](https://user-images.githubusercontent.com/2149815/67762042-cddc5580-fa44-11e9-9755-be2181615b79.png)

but nothing changed anyway.

should i try with powershell?

thanks.

**Comment by andreabisello** [comment]
another way on windows is using testFailureExitCode 0

jest --config ${bamboo.build.working.directory}/jest.config.js --rootDir ${bamboo.build.working.directory} --runInBand --testFailureExitCode 0
